# git-tracker/.github/workflows/update.yml
name: Update Tracker SVG

on:
  repository_dispatch:
    types: [update-tracker]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Generate new SVG
        run: |
          python generate_svg.py
          echo "--- Contents of current directory after SVG generation ---"
          ls -l
          echo "--- End of directory listing ---"
          if [ ! -f tracker.svg ]; then
            echo "ERROR: tracker.svg was NOT created by generate_svg.py!"
            exit 1
          else
            echo "SUCCESS: tracker.svg was created. Displaying first few lines:"
            head tracker.svg
          fi
        env:
          GH_PAT: ${{ secrets.GH_PAT }}
          USERNAME: ${{ vars.USERNAME }}

      - name: Commit and Push SVG
        run: |
          echo "--- Starting Commit and Push step ---"
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

          # Add the file to the staging area
          git add tracker.svg
          echo "--- After git add tracker.svg ---"
          git status # Check status after add

          # Check if there are any staged changes at all (not just tracker.svg specifically)
          # This is more robust as it covers both new files and modifications
          if git diff --staged --quiet; then
            echo "No changes to commit (nothing staged or staged changes are identical to HEAD). Skipping commit."
          else
            echo "Changes are staged. Committing..."
            git commit -m "🔄 Update tracker"
            if [ $? -ne 0 ]; then
              echo "ERROR: git commit failed!"
              exit 1
            fi
            git push
            if [ $? -ne 0 ]; then
              echo "ERROR: git push failed!"
              exit 1
            fi
            echo "Successfully committed and pushed tracker.svg."
          fi